version: "3"
services:
  fluentd:
    build: ./fluentd
    volumes:
      - ./fluentd/conf:/fluentd/etc
    links:
      - elasticsearch
    ports:
      - "24224:24224"
      - "24224:24224/udp"
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: 'elasticsearch'
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    links:
      - elasticsearch
  fakelog:
    build: ./fakelog
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: httpd.access
    links:
      - fluentd
    labels:
      - co.elastic.logs/module=apache2
      - co.elastic.logs/fileset.stdout=access
      - co.elastic.logs/fileset.stderr=error
    depends_on:
      - elasticsearch
      - kibana               